// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bbkzmzdztyzvwxlbojnx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJia3ptemR6dHl6dnd4bGJvam54Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4Nzg4NDYsImV4cCI6MjA3MzQ1NDg0Nn0.RCbNIwu_4wzbkNASqliNlGwbeEPCOIRC3IxUrZG_2Kw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});